#!/usr/bin/env nextflow

/*
###################################################################################################
##################################### Module STAR_Fusion ##########################################
###################################################################################################
*/

nextflow.enable.dsl = 2

/*

#################################### Module STAR_Fusion ###########################################

    This module runs the STAR-Fusion tool to detect fusions from the sub-folder generated by the Create_dir process (Module_OrderFiles_FastQC_rnaSeq_workflow.nf) and returns the directory where the output documents are generated.

*/

if (params.help) {
	log.info ''
	exit 0
}    

process STAR_Fusion_module {

conda '/home/.conda/envs/ipx-fusion'
	
	errorStrategy 'ignore'
	
	input:
	val directory
	
	output:
	stdout
	
	script:
	"""
	R1=\$(ls \$(echo $directory)/*_R1_*.fastq.gz)
	R2=\$(ls \$(echo $directory)/*_R2_*.fastq.gz)
	mkdir -p \$(echo $directory)/STAR_Fusion_results
	
	STAR-Fusion --genome_lib_dir ${params.STAR_fusion_data}\
	            --left_fq \${R1} \
	            --right_fq \${R2} \
	            --output_dir \$(echo $directory)/STAR_Fusion_results
	            
	echo "\$(echo $directory)/STAR_Fusion_results"
	"""
}
